name: Android CI

on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: "MIIKsgIBAzCCClwGCSqGSIb3DQEHAaCCCk0EggpJMIIKRTCCBawGCSqGSIb3DQEHAaCCBZ0EggWZMIIFlTCCBZEGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFC2X9+cIQxmba0RrLcXUa4cfcTfyAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ8n6IrsnCqH0DGK0DpDENegSCBNAzYYaDYLr7oeRU74qUz5W4gOJd2gIPcg+Tr5lphUNzQ6G/sJsshYxhUYt23DyNawdXx8NIbjqobiz1fOyZh19O6NwIqY4FO9K9ZUEbSHAKyB18qUFvL+/9jcN0/fedeOmiKt7eo8s4DtK7s8k6dI13kIEYDL3D8LFYCVR8QA/xsKrnAKb0iGVZCbNXb/7+tx1OXmJ0Nf/Ok+3LEWUR9/VqlzMs5WzQSb5ge1Yko/hIq+Rfl5EjiE8jJH+cuHOjTVder/5pMWUgdcSVnu0YvZsW3jEMvjNvMK3czvuYu5MB7UJlyCOAbMrGsdKVDvZm8EqF4RHqWNROPdRnQAHNjSqJS47Ny5TtgNl8MWMFgVSlL9GzOTwZZpFxMTAZZltkqbo31RFreEENa5xzmLMhYzGsundnQbTyc1b4vMkHzyCH7FIrgjfmNk5ZBs+KQWLrdbwlbXZwx3M5Q+o9PHl5pkAHRkAAc/yZxLEP2JW+J3wR2+e2rVvRFmqXpQ8dkJu/luBdHJ8+J/gqxNPGgx4wDKowZEy9liS7yysonFUQg0W1JFu6mN1sqDv4JAhxV+UHjOgKZdeQD7vUIXOENVYLThZeKdR/CaTM79HaXMj75F3mjJSSQK4pkuLCwl8CRZSpIKfkgpa7eedaZXiagAo+9A7N1MoJz1ZdbPjap02/00X+tvtQXmGTKKpij5orDkAepcEqnh4k2bNY1xooNJWfFASc7EzmL2abK+0v3+ilXByMOWzBfyn53vFlzSsLMbuW6/1el/7BcD4GqwfANC4ileht72uUQ3PoBYprx78lsVMyoz73duWagSkZWzYpYe/hXnHc2XPdzeJ0blVU/RTKFIVHOp79+ERMg8MHuzuKjMo22k1kOFjh6djVI8LMZB74IqJCrM/OLW03puT/UIk0UK4rrHFJwLkZXzuzm21P7D/ybrqZbRQgxgIOp+HoTxF3dUU/fC7Sd9i3z9IkCGDIUE2J70IGKzC5xpq0dGruUvbNW1Mf948ozvaX3HYOqfAJrfiHYseN2eLVd8pTX4dXXm5THcFUD+g0s4kdeKhhicc1OT249uPC9KzLed2ihGjhgcsoyWHBJvvGXVelszrIbOWJHcFAne5i8sWgxc/GMcISB07XE24R4DS3FplsBGUkf5rDoOkKQoNSU9KUW3DWenZN8OiSBwk/9898LJ9o/jf4pr4PZMQFIz8ueGr8ll9DlM8ICzwYPFHq4u5DoLkviyFV2ucmqLrAO3UjtGGpt1VTDVm5++dyLX0rqVZT14D8S32gO1TldfSquTxqf5zWMRrAhDzCJqq85NTE2g6Eh9HaH2jed4i+Obb2ZdVAlNBvsA3XFIsQXK0FiKd7xfELuGRlvzsOhv4ftDE6HPBaGHrlqY6dAEU6nauzwUCfaCFj8x2egfMGX1Ids7ns7UxnuvZWWAPdq9uIjJmi98/8bFKkQ5noIBhRFX4MEKhsOxrsEhTmcTVESvFG847GLuwmlHIUuikQBrsD1EdGAPVcNdVYiDSFHZ/FZvH0GJHtJqpT9qH56s1qdvxlbxOzv9sp5VT/y2mecU14qg7rovZx6qUbpwr5sZqTqeWcp3mvA9JfW4h9TKTH0OuOOgY51RXF5cCvcx5CYwF8PAS+FIzOZLxxmTE+MBkGCSqGSIb3DQEJFDEMHgoAdABhAGcAbQBvMCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE2MzEzMjYzOTkyMjAwggSRBgkqhkiG9w0BBwagggSCMIIEfgIBADCCBHcGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUO/7cGE/VAiPjNPA7NRZZ6B8jiL0CAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBBLxy/ESF6zi5gBz+KsEfyRgIIEAHIt08ZQ+sW82qhlXWr1fCYxc5VAANegiMC4Sk92xct45RsLD/sqvi/97Gp1M3vAWGez2htjdNFkuo9rWB4QQo0pdYSwwuavJwZoRE3+9u/l/2OPuCCLwWHvYE0LaOWCn1tq/z48jcr8RMsQ+RO+YsDPJWHzkE36lh9QAyUAWHJ02tpICEiIPdF2AcziPe0o876Wx9/PqD5VSEfHmw1NStaNxPqHux4kUto7qwDaewWACHbVEiC3YJPBZwcO9ZozLAEkCZ8pYUQfPIfRxzEEI+/6DEjMhv/+//DbzLQyWUS0M2vvFT2qghjNDHkZjATcr6RgBdKVG0xrC2fPyARUtvmC9k+nM+XDui/N1qgJN87gYjj/sqARGZSjEgL/EWggvPrEbD6Xo5iqUqTqh3mQt4C/QmY3l+V2EJjDCjW6X2GKSLZlxb0TGCv5Xaufw/sVitp+Xf532Kl1217ePboOXZthPbdxVWjUIaIRmhtLNokdWgctz8Lbx7bgUjkymaSdRS6KH9fikl1tFo4nmtzozBGswOLI5gkZGb6pqpPViI/+dy8VNpOFyTkUL9+z8yREL0R788U4iR0DnPP0TojoydzWilY0QceoxaRiOxZX8pN6JzbxzLpFvQP0fxS5AFW7w5iUMwVaOuwG9uXIIrdbQ+wW9wFAdikIZghZlF9jZ9F4NNppYHVjs0ChMY1/q30lWmaSVXhf4uvU6u6QJKMi2Re+scOOWoQWbs9VLQv5lQD4W9xYosyXioZnmnmIYLiiDHIMLkXPo53HJXCQZjwy5C2hEsBUtnK+q0viU2mbBtQcnzEEXKs1dt8rq6fVu0Pei7ZDCGlJUjAYWJt3UmcMCiDiqXjvyOj0SgMuuywzAEisFaVxAbgieCZjtkkF1QF5Les+HS9wZnEnvnztqOFSZjMrPWYkbxLr9/9gQRCbKbPQodCwO2qQu5jDrHHw58UvCU+ujpyXKd5yy5KaUphmApMFtXQo9BMVBOWji03IvTouTb1J33Btxt+2qH8UfzE12T3FJeFvnorwMT+2TPnz50lTQU6WytifRw5B30xdPOc5BDnLP7/DYHTqPun/5d9jf4/mnAedkrHl5U2enTAyIFR+Vdlq8jwBTF0c9+JdRMJEUNnIf3w2DpYk9pBSMlN2X9akEJ28ut1UczGkwpO00td71xiL0/zsF4GQQ+xmwOG9sBFNCL8zw1rJedC2U/vfUExx5fzzMxCr4v1NwighyNM2NA9Zs7eWN2vEt+jbczEFqZQ/HHjmvm6u/rN4GQYMMCeVgd7MW7fO6KWnnTwnlvd+M2EWV/3BkdcvFMsb8o1HZRTytn4NM0FPqqd1ldOU/BF0ovMtxvrfW0N+6bDN0N4wTTAxMA0GCWCGSAFlAwQCAQUABCBaOYG7XcP7H1xvuIEt7PVGa8yNIxqJWnCR3ZtRk8KkwAQUDxesv5wYKBXGug3fL1zC8j1PkzkCAicQ"
        alias: "tagmo"
        keyStorePassword: "hiddenramblings"
        keyPassword: "hiddenramblings"
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"
        
    - name: Retrieve commit short hash
      run: |
         GIT_HASH=$(git rev-parse --short HEAD)
         echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: TagMo-${{ env.GIT_HASH }}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

    - uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: TagMo-${{ env.GIT_HASH }}
        files: ${{steps.sign_app.outputs.signedReleaseFile}}
